### ISSUE TITLE
源码可以使用到ios项目中吗？

### ISSUE THREAD

**Issue by huomeina** [Xing94/fil-bls-sign-rs#2]
请问这个源码可以使用到ios项目中吗？我尝试可以编译出.a文件添加到项目中，但是我不知道怎么直接调用方法？

**Comment by Xing94** [comment]
ios你看我文档说明，跟着里面的方法来，就能拿到了

**Comment by huomeina** [comment]
因为我看您这个android.rs文件里的方法，我写了一个ios.rs调用，

#[no_mangle]
pub unsafe fn filPrivateKeyPublicKey(private_key_hex: *const c_char) -> *mut c_char {


	let private_key = "79acb1eb7de18475249187ac6072c01c2587547a11eedcf30c609619a62f1b2f";
//	let private_key = "我是说个";
    let decode_private_key = catch_unwind(|| {
        hex::decode(private_key)
    }).unwrap();


    if decode_private_key.is_ok() {
        let raw_private_key_ptr: *const u8 = decode_private_key.unwrap().as_ptr();

        let public_key = (*fil_private_key_public_key(raw_private_key_ptr)).public_key.inner;

        let out_byte = from_raw_parts(&public_key[0], PUBLIC_KEY_BYTES);
        println!("success {}", hex::encode(out_byte));
        CString::new(hex::encode(out_byte).to_owned()).unwrap().into_raw()
    } else {
        println!("failed {}", "这是一个错误啊");
        CString::new("000000").unwrap().into_raw()
    }
}




我不太懂rust,我生成了.a文件使用，每次运行调用这个方法得到的结果都会改变，不理解我写死的私钥，得到的公钥为啥会变化呢？
